Added contact form as per issue #4
Cuji12/jw-8.com pull request #11
Opened 2023-09-13 20:01 UTC by PCloughster

Added contact form + validation and recaptcha to the project

2023-09-16 08:55 UTC, Cuji12 requested changes
Looks good, just some minor bits throughout but otherwise LGTM :mage:

2023-09-16 08:55 UTC, Cuji12 commented on app/Http/Controllers/ContactController.php
> +    public function show(){
Does this get used? Or are we not using the contact method in the SiteController to display the contact page?

2023-09-16 08:55 UTC, Cuji12 commented on app/.DS_Store
Add DS_Store to .gitignore, they're just MacOS file directory config setting files afaik.

2023-09-16 08:55 UTC, Cuji12 commented on app/Http/Requests/ContactFormRequest.php
> +namespace App\Http\Requests;
Nitpicky but add new lines between separate things like namespace, use and class

2023-09-16 08:55 UTC, Cuji12 commented on app/Models/Recipient.php
> +class Recipient extends Model
Same here with new lines

2023-09-16 08:55 UTC, Cuji12 commented on app/Notifications/ContactFormMessage.php
> +    protected $message;
Move variables below use statements

2023-09-16 08:55 UTC, Cuji12 commented on app/Nova/ContactPage.php
> +        'id',
This is something I forgot to do with the other Nova resources, but we want to be able to search by the title too.

2023-09-16 08:55 UTC, Cuji12 commented on app/Nova/User.php
> +            Gravatar::make()->maxWidth(50),
Remove Gravatar here

2023-09-16 08:55 UTC, Cuji12 commented on images/about-us-image.jpg
Does this get used somewhere? If it doesn't, just remove it however if it does - move it to public/images folder. Anything outside of the public folder isn't accessible over the internet because both Apache and Nginx (generally what you'd use to serve a Laravel application) both have a config: Document Root and Root Directive respectively that prevent requests to resources outside the defined directory, which by default is the public directory. 

If you need to access assets easily in Blade templates or anywhere in your Laravel application, you should use the asset helper like so: `asset('images/about-us-image.jpg')`.

2023-09-16 08:55 UTC, Cuji12 commented on images/about-us-image.jpg
Just an added note to that, ideally we wouldn't store any assets in the public directory but because it's a small project it's fine honestly. Usually though, we'd want to store them in the storage directory and create a symbolic link between `/storage` and `/public/storage`. It makes it easier to make use of different storage engines like S3 etc.

2023-09-16 08:55 UTC, Cuji12 commented on resources/views/layouts/main.blade.php
> +                        Contact Us
Don't forget to add the Contact Us nav link to both mobile / desktop

2023-09-16 08:55 UTC, Cuji12 commented on routes/web.php
> +    Route::post('/contact', [ContactController::class, 'mailContactForm']);
Remove this from the SiteController context, it expects all routes within that to be methods of SiteController

2023-10-01 15:21 UTC, PCloughster commented on app/.DS_Store
Added to git ignore :)

2023-10-01 15:21 UTC, PCloughster commented on app/Http/Requests/ContactFormRequest.php
> +namespace App\Http\Requests;
sorted will do in future

2023-10-01 15:24 UTC, PCloughster commented on app/Nova/ContactPage.php
> +        'id',
Sorted

2023-10-01 15:24 UTC, PCloughster commented on app/Nova/User.php
> +            Gravatar::make()->maxWidth(50),
Gone

2023-10-01 15:25 UTC, PCloughster commented on images/about-us-image.jpg
No sorry was just messing about with nova not used at all :)

2023-10-01 15:28 UTC, PCloughster commented on resources/views/layouts/main.blade.php
> +                        Contact Us
God brainfart here, sorted

2023-10-01 15:37 UTC, PCloughster commented on routes/web.php
> +    Route::post('/contact', [ContactController::class, 'mailContactForm']);
Removed from site controller added a new controller context

2023-10-02 05:58 UTC, PCloughster commented on app/Http/Controllers/ContactController.php
> +    public function show(){
Yeah this gets used but so does the contact method in the sitecontroller one to display the page, one to handle post requests and display the messages of success/failure for the contact form

2023-10-02 05:59 UTC, PCloughster commented on app/Notifications/ContactFormMessage.php
> +    protected $message;
Might be missing something but that's how its layed out in this file

2023-10-04 17:39 UTC, merged